import { expect } from "@playwright/test";

import { idToDelete, validPostData } from "./constants";

export function validateJsonResponseGenderize(responseBody){

    expect(responseBody).toHaveProperty('count');

    expect(responseBody).toHaveProperty('name');

    expect(responseBody).toHaveProperty('gender');

    expect(responseBody).toHaveProperty('probability');
}

export function validateDummyApiPostRequest(responseBody, responseData){

    expect(responseBody).toHaveProperty('status', 'success');

    expect(responseBody).toHaveProperty('message', 'Successfully! Record has been added.');

    expect(responseData).toHaveProperty('name', validPostData.name);

    expect(responseData).toHaveProperty('salary', validPostData.salary);

    expect(responseData).toHaveProperty('age', validPostData.age);

    expect(responseData).toHaveProperty('id'); // ID is generated by the API, so just check its presence
};

export function validateDummyApiPutRequest(responseBody, responseData){

    expect(responseBody).toHaveProperty('status', 'success');

    expect(responseBody).toHaveProperty('message', 'Successfully! Record has been updated.');

    expect(responseData).toHaveProperty('name', validPostData.name);

    expect(responseData).toHaveProperty('salary', validPostData.salary);

    expect(responseData).toHaveProperty('age', validPostData.age);
}

export function validateDummyApiDeleteRequest(responseBody){

    expect(responseBody).toHaveProperty('status', 'success');

    expect(responseBody).toHaveProperty('data', idToDelete);

    expect(responseBody).toHaveProperty('message', "Successfully! Record has been deleted");
}